[project]
name = 'Blockchain-basedGaming'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-game-transfer]
path = 'contracts/cross-game-transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.game-items]
path = 'contracts/game-items.clar'
clarity_version = 2
epoch = 2.5

[contracts.player-economy]
path = 'contracts/player-economy.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
